### ISSUE TITLE
Highlight is too subtle when using light background theme

### ISSUE THREAD

**Issue by dandavison** [leonhard-s/python-sphinx-highlighter#14]
Hi, thanks for the extension. The highlight colors only seem to be clearly visible for dark themes.

E.g. with `Light Modern`

<img width="663" alt="image" src="https://github.com/user-attachments/assets/c138c588-70d1-4e6e-88ba-70dcfd7ee84b">

vs `Dark Modern`

<img width="655" alt="image" src="https://github.com/user-attachments/assets/dd96ae16-c91d-40b5-9913-48d321dbd485">

**Comment by leonhard-s** [comment]
Hi, thank you for your issue.

Unfortunately, the exact colours chosen are not something this extension has control over. The current version only injects additional TextMate scopes into the docstring, which are then coloured according to the theme.

I have toyed with customizing the chosen tags to "look nice" with the themes I prefer, but doing so can have adverse effects when other themes are used. So instead, this extension uses reasonable scope names (`entity.name.tag.sphinx`, `entity.name.role.sphinx`, ...) and leaves the exact colours up to the user's theme.

To fix issues with a given theme, you should be able to override these `*.sphinx` tags globally or per-theme in your user settings: [Customizing editor syntax highlighting](https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting).

**Comment by dandavison** [comment]
Hi, that's perfect, thanks! In fact, that's even better than having a setting in the extension, since you've introduced me to `tokenColorCustomizations`, which I hadn't played with previously.

So, in case it's useful for anyone else, I'm using something like
```json
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "entity.name.tag.sphinx",
        "settings": {
          "foreground": "#0e61a5"
        }
      },
      {
        "scope": "entity.name.role.sphinx",
        "settings": {
          "foreground": "#179648"
        }
      }
    ]
  },
```

<img width="644" alt="image" src="https://github.com/user-attachments/assets/f2a4f828-c2f5-4666-b443-70e890725311">
